// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: umsg.proto

#ifndef PROTOBUF_INCLUDED_umsg_2eproto
#define PROTOBUF_INCLUDED_umsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_umsg_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_umsg_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_umsg_2eproto();
namespace vcf {
class Initial_msg;
class Initial_msgDefaultTypeInternal;
extern Initial_msgDefaultTypeInternal _Initial_msg_default_instance_;
class Initial_msg_Cmd;
class Initial_msg_CmdDefaultTypeInternal;
extern Initial_msg_CmdDefaultTypeInternal _Initial_msg_Cmd_default_instance_;
class Initial_msg_Prm;
class Initial_msg_PrmDefaultTypeInternal;
extern Initial_msg_PrmDefaultTypeInternal _Initial_msg_Prm_default_instance_;
class Operational_msg;
class Operational_msgDefaultTypeInternal;
extern Operational_msgDefaultTypeInternal _Operational_msg_default_instance_;
}  // namespace vcf
namespace google {
namespace protobuf {
template<> ::vcf::Initial_msg* Arena::CreateMaybeMessage<::vcf::Initial_msg>(Arena*);
template<> ::vcf::Initial_msg_Cmd* Arena::CreateMaybeMessage<::vcf::Initial_msg_Cmd>(Arena*);
template<> ::vcf::Initial_msg_Prm* Arena::CreateMaybeMessage<::vcf::Initial_msg_Prm>(Arena*);
template<> ::vcf::Operational_msg* Arena::CreateMaybeMessage<::vcf::Operational_msg>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace vcf {

// ===================================================================

class Initial_msg_Cmd : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vcf.Initial_msg.Cmd) */ {
 public:
  Initial_msg_Cmd();
  virtual ~Initial_msg_Cmd();

  Initial_msg_Cmd(const Initial_msg_Cmd& from);

  inline Initial_msg_Cmd& operator=(const Initial_msg_Cmd& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Initial_msg_Cmd(Initial_msg_Cmd&& from) noexcept
    : Initial_msg_Cmd() {
    *this = ::std::move(from);
  }

  inline Initial_msg_Cmd& operator=(Initial_msg_Cmd&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Initial_msg_Cmd& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Initial_msg_Cmd* internal_default_instance() {
    return reinterpret_cast<const Initial_msg_Cmd*>(
               &_Initial_msg_Cmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Initial_msg_Cmd* other);
  friend void swap(Initial_msg_Cmd& a, Initial_msg_Cmd& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Initial_msg_Cmd* New() const final {
    return CreateMaybeMessage<Initial_msg_Cmd>(NULL);
  }

  Initial_msg_Cmd* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Initial_msg_Cmd>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Initial_msg_Cmd& from);
  void MergeFrom(const Initial_msg_Cmd& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Initial_msg_Cmd* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string _name = 2;
  void clear__name();
  static const int kNameFieldNumber = 2;
  const ::std::string& _name() const;
  void set__name(const ::std::string& value);
  #if LANG_CXX11
  void set__name(::std::string&& value);
  #endif
  void set__name(const char* value);
  void set__name(const char* value, size_t size);
  ::std::string* mutable__name();
  ::std::string* release__name();
  void set_allocated__name(::std::string* _name);

  // double _value = 4;
  void clear__value();
  static const int kValueFieldNumber = 4;
  double _value() const;
  void set__value(double value);

  // uint32 _from = 1;
  void clear__from();
  static const int kFromFieldNumber = 1;
  ::google::protobuf::uint32 _from() const;
  void set__from(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:vcf.Initial_msg.Cmd)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr _name_;
  double _value_;
  ::google::protobuf::uint32 _from_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_umsg_2eproto;
};
// -------------------------------------------------------------------

class Initial_msg_Prm : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vcf.Initial_msg.Prm) */ {
 public:
  Initial_msg_Prm();
  virtual ~Initial_msg_Prm();

  Initial_msg_Prm(const Initial_msg_Prm& from);

  inline Initial_msg_Prm& operator=(const Initial_msg_Prm& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Initial_msg_Prm(Initial_msg_Prm&& from) noexcept
    : Initial_msg_Prm() {
    *this = ::std::move(from);
  }

  inline Initial_msg_Prm& operator=(Initial_msg_Prm&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Initial_msg_Prm& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Initial_msg_Prm* internal_default_instance() {
    return reinterpret_cast<const Initial_msg_Prm*>(
               &_Initial_msg_Prm_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Initial_msg_Prm* other);
  friend void swap(Initial_msg_Prm& a, Initial_msg_Prm& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Initial_msg_Prm* New() const final {
    return CreateMaybeMessage<Initial_msg_Prm>(NULL);
  }

  Initial_msg_Prm* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Initial_msg_Prm>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Initial_msg_Prm& from);
  void MergeFrom(const Initial_msg_Prm& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Initial_msg_Prm* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 _vartype = 1;
  void clear__vartype();
  static const int kVartypeFieldNumber = 1;
  ::google::protobuf::uint32 _vartype() const;
  void set__vartype(::google::protobuf::uint32 value);

  // int32 _min = 2;
  void clear__min();
  static const int kMinFieldNumber = 2;
  ::google::protobuf::int32 _min() const;
  void set__min(::google::protobuf::int32 value);

  // int32 _max = 3;
  void clear__max();
  static const int kMaxFieldNumber = 3;
  ::google::protobuf::int32 _max() const;
  void set__max(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:vcf.Initial_msg.Prm)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _vartype_;
  ::google::protobuf::int32 _min_;
  ::google::protobuf::int32 _max_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_umsg_2eproto;
};
// -------------------------------------------------------------------

class Initial_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vcf.Initial_msg) */ {
 public:
  Initial_msg();
  virtual ~Initial_msg();

  Initial_msg(const Initial_msg& from);

  inline Initial_msg& operator=(const Initial_msg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Initial_msg(Initial_msg&& from) noexcept
    : Initial_msg() {
    *this = ::std::move(from);
  }

  inline Initial_msg& operator=(Initial_msg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Initial_msg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Initial_msg* internal_default_instance() {
    return reinterpret_cast<const Initial_msg*>(
               &_Initial_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Initial_msg* other);
  friend void swap(Initial_msg& a, Initial_msg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Initial_msg* New() const final {
    return CreateMaybeMessage<Initial_msg>(NULL);
  }

  Initial_msg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Initial_msg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Initial_msg& from);
  void MergeFrom(const Initial_msg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Initial_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Initial_msg_Cmd Cmd;
  typedef Initial_msg_Prm Prm;

  // accessors -------------------------------------------------------

  // repeated .vcf.Initial_msg.Cmd cmd = 5;
  int cmd_size() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 5;
  ::vcf::Initial_msg_Cmd* mutable_cmd(int index);
  ::google::protobuf::RepeatedPtrField< ::vcf::Initial_msg_Cmd >*
      mutable_cmd();
  const ::vcf::Initial_msg_Cmd& cmd(int index) const;
  ::vcf::Initial_msg_Cmd* add_cmd();
  const ::google::protobuf::RepeatedPtrField< ::vcf::Initial_msg_Cmd >&
      cmd() const;

  // repeated .vcf.Initial_msg.Prm prm = 6;
  int prm_size() const;
  void clear_prm();
  static const int kPrmFieldNumber = 6;
  ::vcf::Initial_msg_Prm* mutable_prm(int index);
  ::google::protobuf::RepeatedPtrField< ::vcf::Initial_msg_Prm >*
      mutable_prm();
  const ::vcf::Initial_msg_Prm& prm(int index) const;
  ::vcf::Initial_msg_Prm* add_prm();
  const ::google::protobuf::RepeatedPtrField< ::vcf::Initial_msg_Prm >&
      prm() const;

  // string _msg = 4;
  void clear__msg();
  static const int kMsgFieldNumber = 4;
  const ::std::string& _msg() const;
  void set__msg(const ::std::string& value);
  #if LANG_CXX11
  void set__msg(::std::string&& value);
  #endif
  void set__msg(const char* value);
  void set__msg(const char* value, size_t size);
  ::std::string* mutable__msg();
  ::std::string* release__msg();
  void set_allocated__msg(::std::string* _msg);

  // uint32 _seqNo = 1;
  void clear__seqno();
  static const int kSeqNoFieldNumber = 1;
  ::google::protobuf::uint32 _seqno() const;
  void set__seqno(::google::protobuf::uint32 value);

  // uint32 _version = 2;
  void clear__version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::uint32 _version() const;
  void set__version(::google::protobuf::uint32 value);

  // int32 _result = 3;
  void clear__result();
  static const int kResultFieldNumber = 3;
  ::google::protobuf::int32 _result() const;
  void set__result(::google::protobuf::int32 value);

  // uint32 _cycle = 7;
  void clear__cycle();
  static const int kCycleFieldNumber = 7;
  ::google::protobuf::uint32 _cycle() const;
  void set__cycle(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:vcf.Initial_msg)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::vcf::Initial_msg_Cmd > cmd_;
  ::google::protobuf::RepeatedPtrField< ::vcf::Initial_msg_Prm > prm_;
  ::google::protobuf::internal::ArenaStringPtr _msg_;
  ::google::protobuf::uint32 _seqno_;
  ::google::protobuf::uint32 _version_;
  ::google::protobuf::int32 _result_;
  ::google::protobuf::uint32 _cycle_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_umsg_2eproto;
};
// -------------------------------------------------------------------

class Operational_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vcf.Operational_msg) */ {
 public:
  Operational_msg();
  virtual ~Operational_msg();

  Operational_msg(const Operational_msg& from);

  inline Operational_msg& operator=(const Operational_msg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Operational_msg(Operational_msg&& from) noexcept
    : Operational_msg() {
    *this = ::std::move(from);
  }

  inline Operational_msg& operator=(Operational_msg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Operational_msg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Operational_msg* internal_default_instance() {
    return reinterpret_cast<const Operational_msg*>(
               &_Operational_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Operational_msg* other);
  friend void swap(Operational_msg& a, Operational_msg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Operational_msg* New() const final {
    return CreateMaybeMessage<Operational_msg>(NULL);
  }

  Operational_msg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Operational_msg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Operational_msg& from);
  void MergeFrom(const Operational_msg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int